services:
  next:
    build:
      context: ./recette
      dockerfile: Dockerfile
    container_name: next_app
    ports:
      - "3000:3000"
    volumes:
      - ./recette:/usr/app/recette
      - /usr/app/recette/node_modules
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=${NODE_ENV}
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    entrypoint: ["/ollama-entrypoint.sh"]

volumes:
  ollama_data:
